su2hmc: INCLUDE/coord.h File Reference
coord.h File Reference
Header for routines related to lattice sites.
#include <math.h>
#include <sizes.h>
Functions
int Addrc (unsigned int *iu, unsigned int *id)
Loads the addresses required during the update.
int ia (int x, int y, int z, int t)
Described as a 21st Century address calculator, it gets the memory address of an array entry.
int Check_addr (unsigned int *table, int lns, int lnt, int imin, int imax)
int Index2lcoord (int index, int *coord)
Converts the index of a point in memory to the equivalent point in the 4 dimensional array, where the time index is the last coordinate in the array.
int Index2gcoord (int index, int *coord)
Converts the index of a point in memory to the equivalent point in the 4 dimensional array, where the time index is the last coordinate in the array.
int Coord2lindex (int ix, int iy, int iz, int it)
Converts the coordinates of a local lattice point to its index in the computer memory.
int Coord2gindex (int ix, int iy, int iz, int it)
Converts the coordinates of a global lattice point to its index in the computer memory.
int Testlcoord (int cap)
Tests if the local coordinate transformation functions are working.
int Testgcoord (int cap)
This is completely new and missing from the original code.
Variables
unsigned int * hu
Up halo indices.
unsigned int * hd
Down halo indices.
unsigned int * h1u
Up halo starting element.
unsigned int * h1d
Down halo starting element.
unsigned int * halosize
Array containing the size of the halo in each direction.
Detailed Description
Header for routines related to lattice sites.
Function Documentation
Addrc()
int Addrc (unsigned int * iu, unsigned int * id)
Loads the addresses required during the update.
Parameters
iu Upper halo indices
id Lower halo indices
See also
hu, hd, h1u, h1d, h2u, h2d, halosize
Returns
Zero on success, integer error code otherwise
References AVX, comm, h1d, h1u, halo, HALOLIM, halosize, halot, halox, haloy, haloz, hd, hu, ia(), ksize, ksizet, ksizex, ksizey, ksizez, kvol, and ndim.
Check_addr()
int Check_addr (unsigned int * table, int lns, int lnt, int imin, int imax)
Checks that the addresses are within bounds before an update
Parameters
table Pointer to the table in question
lns Size of each spacial dimension
lnt Size of the time dimension
imin Lower bound for element of the table
imax Upper bound for an element of the table
Returns
Zero on success, integer error code otherwise.
References BOUNDERROR, comm, and ndim.
Coord2gindex()
int Coord2gindex (int ix, int iy, int iz, int it) inline
Converts the coordinates of a global lattice point to its index in the computer memory.
This is a rather nuanced function, as C and Fortran are rather different in how they store arrays. C starts with index 0 and Fortran (by default) starts with index 1
Also C and Fortran store data in the opposite memory order so be careful when calling this function!
Parameters
ix,iy,iz,it Index in each direction
Returns:
int index: The position of the point
References nx, ny, and nz.
Coord2lindex()
int Coord2lindex (int ix, int iy, int iz, int it) inline
Converts the coordinates of a local lattice point to its index in the computer memory.
This is a rather nuanced function, as C and Fortran are rather different in how they store arrays. C starts with index 0 and Fortran (by default) starts with index 1
Also C and Fortran store data in the opposite memory order so be careful when calling this function!
Parameters
ix,iy,iz,it Index in each direction
Returns:
int index: The position of the point
References ksizet, ksizey, and ksizez.
ia()
int ia (int x, int y, int z, int t) inline
Described as a 21st Century address calculator, it gets the memory address of an array entry.
Parameters
x,y,z,t The coordinates
Returns
An integer corresponding to the position of the entry in a flattened row-major array.
Todo
Future... Switch for Row and column major, and zero or one indexing
References ksizet, ksizex, ksizey, and ksizez.
Index2gcoord()
int Index2gcoord (int index, int * coord) inline
Converts the index of a point in memory to the equivalent point in the 4 dimensional array, where the time index is the last coordinate in the array.
This is a rather nuanced function, as C and Fortran are rather different in how they store arrays. C starts with index 0 and Fortran (by default) starts with index 1
Also C and Fortran store data in the opposite memory order so be careful when calling this function!
Parameters
index The index of the point as stored linearly in computer memory
coord The 4-array for the coordinates. The first three spots are for the time index.
Returns
Zero on success. Integer Error code otherwise
References nt, ny, and nz.
Index2lcoord()
int Index2lcoord (int index, int * coord) inline
Converts the index of a point in memory to the equivalent point in the 4 dimensional array, where the time index is the last coordinate in the array.
This is a rather nuanced function, as C and Fortran are rather different in how they store arrays. C starts with index 0 and Fortran (by default) starts with index 1
Also C and Fortran store data in the opposite memory order so be careful when calling this function!
Parameters
index The index of the point as stored linearly in computer memory
coord The 4-array for the coordinates. The first three spots are for the time index.
Returns
Zero on success. Integer Error code otherwise
References ksizet, ksizey, and ksizez.
Testgcoord()
int Testgcoord (int cap)
This is completely new and missing from the original code.
We test the coordinate conversion functions by doing the following
Convert from int to gcoord (new)
Convert from gcoord to int (also new) and compare to input. If we get the same value we started with then we're probably doing something right
The code is basically the same as the previous function with different magic numbers.
Parameters
cap The max value the index can take on. Should be the size of our array
Returns
Zero on success, integer error code otherwise
References comm, Index2gcoord(), and INDTOCOORD.
Testlcoord()
int Testlcoord (int cap)
Tests if the local coordinate transformation functions are working.
Going to expand a little on the original here and do the following
Convert from int to lcoord (the original code) And the planned additional features
Convert from lcoord to int (new, function doesn't exist in the original If we get the same value we started with then we're probably doing something right.
Parameters
cap The max value the index can take on. Should be the size of the array
Returns
Zero on success, integer error code otherwise.
References comm, Index2lcoord(), and INDTOCOORD.
Variable Documentation
h1d
unsigned int* h1d extern
Down halo starting element.
h1u
unsigned int* h1u extern
Up halo starting element.
halosize
unsigned int* halosize extern
Array containing the size of the halo in each direction.
hd
unsigned int* hd extern
Down halo indices.
hu
unsigned int* hu extern
Up halo indices.