su2hmc: production_c/fermionic.c File Reference
fermionic.c File Reference
Code for fermionic observables.
#include <matrices.h>
#include <random.h>
#include <su2hmc.h>
Functions
int Measure (double *pbp, double *endenf, double *denf, Complex *qq, Complex *qbqb, double res, int *itercg, Complex *u11t, Complex *u12t, Complex_f *u11t_f, Complex_f *u12t_f, unsigned int *iu, unsigned int *id, Complex *gamval, Complex_f *gamval_f, int *gamin, double *dk4m, double *dk4p, float *dk4m_f, float *dk4p_f, Complex_f jqq, float akappa, Complex *Phi, Complex *R1)
Calculate fermion expectation values via a noisy estimator.
Detailed Description
Code for fermionic observables.
Function Documentation
Measure()
int Measure (double * pbp, double * endenf, double * denf, Complex * qq, Complex * qbqb, double res, int * itercg, Complex * u11t, Complex * u12t, Complex_f * u11t_f, Complex_f * u12t_f, unsigned int * iu, unsigned int * id, Complex * gamval, Complex_f * gamval_f, int * gamin, double * dk4m, double * dk4p, float * dk4m_f, float * dk4p_f, Complex_f jqq, float akappa, Complex * Phi, Complex * R1)
Calculate fermion expectation values via a noisy estimator.
Matrix inversion via conjugate gradient algorithm Solves \(MX=X_1\) (Numerical Recipes section 2.10 pp.70-73)
uses NEW lookup tables ** Implemented in Congradp()
Parameters
pbp \(\langle\bar{\Psi}\Psi\rangle\)
endenf Energy density
denf Number Density
qq Diquark condensate
qbqb Antidiquark condensate
res Conjugate Gradient Residue
itercg Iterations of Conjugate Gradient
u11t,u12t Double precisiongauge field
u11t_f,u12t_f Single precision gauge fields
iu,id Lattice indices
gamval Gamma matrices
gamval_f Gamma matrices (float)
gamin Indices for Dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
dk4m_f \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p_f \(\left(1-\gamma_0\right)e^\mu\)
jqq Diquark source
akappa Hopping parameter
Phi Pseudofermion field
R1 A useful array for holding things that was already assigned in main. In particular, we'll be using it to catch the output of \(M^\dagger\Xi\) before the inversion, then used to store the output of the inversion
Returns
Zero on success, integer error code otherwise
References AVX, Complex, Complex_f, Congradp(), conj, creal, DOWN, Dslashd_f(), Gauss_c(), gvol, ITERLIM, kferm, kfermHalo, kvol, nc, ndim, ndirac, ngorkov, Par_dsum(), UP, and ZHalo_swap_dir().