su2hmc: INCLUDE/matrices.h File Reference
matrices.h File Reference
Matrix multiplication and related declarations.
#include <par_mpi.h>
#include <su2hmc.h>
Functions
int Dslash (Complex *phi, Complex *r, Complex *u11t, Complex *u12t, unsigned int *iu, unsigned int *id, Complex *gamval, int *gamin, double *dk4m, double *dk4p, Complex_f jqq, float akappa)
Evaluates \(\Phi=M r\) in double precision.
int Dslashd (Complex *phi, Complex *r, Complex *u11t, Complex *u12t, unsigned int *iu, unsigned int *id, Complex *gamval, int *gamin, double *dk4m, double *dk4p, Complex_f jqq, float akappa)
Evaluates \(\Phi=M^\dagger r\) in double precision.
int Hdslash (Complex *phi, Complex *r, Complex *u11t[2], unsigned int *iu, unsigned int *id, Complex *gamval, int *gamin, double *dk[2], float akappa)
Evaluates \(\Phi=M r\) in double precision.
int Hdslashd (Complex *phi, Complex *r, Complex *u11t, Complex *u12t, unsigned int *iu, unsigned int *id, Complex *gamval, int *gamin, double *dk4m, double *dk4p, float akappa)
Evaluates \(\Phi=M^\dagger r\) in double precision.
int Dslash_f (Complex_f *phi, Complex_f *r, Complex_f *u11t, Complex_f *u12t, unsigned int *iu, unsigned int *id, Complex_f *gamval, int *gamin, float *dk[2], Complex_f jqq, float akappa)
Evaluates \(\Phi=M r\) in single precision.
int Dslashd_f (Complex_f *phi, Complex_f *r, Complex_f *u11t, Complex_f *u12t, unsigned int *iu, unsigned int *id, Complex_f *gamval, int *gamin, float *dk[2], Complex_f jqq, float akappa)
Evaluates \(\Phi=M^\dagger r\) in single precision.
int Hdslash_f (Complex_f *phi, Complex_f *r, Complex_f *ut[2], unsigned int *iu, unsigned int *id, Complex_f *gamval, int *gamin, float *dk[2], float akappa)
Evaluates \(\Phi=M r\) in single precision.
int Hdslashd_f (Complex_f *phi, Complex_f *r, Complex_f *ut[2], unsigned int *iu, unsigned int *id, Complex_f *gamval, int *gamin, float *dk[2], float akappa)
Evaluates \(\Phi=M^\dagger r\) in single precision.
void Transpose_z (Complex *out, const int, const int)
void Transpose_c (Complex_f *out, const int, const int)
void Transpose_d (double *out, const int, const int)
void Transpose_f (float *out, const int, const int)
void Transpose_I (int *out, const int, const int)
void Transpose_U (unsigned int *out, const int, const int)
Detailed Description
Matrix multiplication and related declarations.
Definition in file matrices.h.
Function Documentation
Dslash()
int Dslash (Complex * phi, Complex * r, Complex * u11t, Complex * u12t, unsigned int * iu, unsigned int * id, Complex * gamval, int * gamin, double * dk4m, double * dk4p, Complex_f jqq, float akappa)
Evaluates \(\Phi=M r\) in double precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
jqq Diquark source
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 19 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M r@f) in double precision.
    *
    * @param   phi:        The product
    * @param   r:          The array being acted on by M
    * @param   u11t:    First colour trial field
    * @param   u12t:    Second colour trial field
    * @param   iu:         Upper halo indices
    * @param   id:         Lower halo indices
    * @param   gamval:  Gamma matrices
    * @param   gamin:      Indices for dirac terms
    * @param   dk4m:
    * @param   dk4p:
    * @param   jqq:        Diquark source
    * @param   akappa:     Hopping parameter
    *
    * @see ZHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Dslash";
   //Get the halos in order
#if(nproc>1)
   ZHalo_swap_all(r, 16);
#endif
   //Mass term
   //Diquark Term (antihermitian)
#ifdef __NVCC__
   cuDslash(phi,r,u11t,u12t,iu,id,gamval,gamin,dk4m,dk4p,jqq,akappa,dimGrid,dimBlock);
#else
   memcpy(phi, r, kferm*sizeof(Complex));
#pragma omp parallel for
   for(int i=0;i<kvol;i++){
#pragma omp simd aligned(phi,r,gamval:AVX)
      for(int idirac = 0; idirac<ndirac; idirac++){
         int igork = idirac+4;
         Complex a_1, a_2;
         a_1=conj(jqq)*gamval[4*ndirac+idirac];
         //We subtract a_2, hence the minus
         a_2=-jqq*gamval[4*ndirac+idirac];
         phi[(i*ngorkov+idirac)*nc]+=a_1*r[(i*ngorkov+igork)*nc+0];
         phi[(i*ngorkov+idirac)*nc+1]+=a_1*r[(i*ngorkov+igork)*nc+1];
         phi[(i*ngorkov+igork)*nc+0]+=a_2*r[(i*ngorkov+idirac)*nc];
         phi[(i*ngorkov+igork)*nc+1]+=a_2*r[(i*ngorkov+idirac)*nc+1];
      }
      //Spacelike terms. Here's hoping I haven't put time as the zeroth component somewhere!
#ifndef NO_SPACE
      for(int mu = 0; mu <3; mu++){
         int did=id[mu+ndim*i]; int uid = iu[mu+ndim*i];
#pragma omp simd aligned(phi,r,u11t,u12t,gamval:AVX)
         for(int igorkov=0; igorkov<ngorkov; igorkov++){
            //FORTRAN had mod((igorkov-1),4)+1 to prevent issues with non-zero indexing in the dirac term.
            int idirac=igorkov%4;
            int igork1 = (igorkov<4) ? gamin[mu*ndirac+idirac] : gamin[mu*ndirac+idirac]+4;
            //Can manually vectorise with a pragma?
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
            phi[(i*ngorkov+igorkov)*nc]+=-akappa*(u11t[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc]+\
                  u12t[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc+1]+\
                  conj(u11t[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]-\
                  u12t[did*ndim+mu]*r[(did*ngorkov+igorkov)*nc+1])+\
                                         //Dirac term. Reminder! gamval was rescaled by kappa when we defined it
                                         gamval[mu*ndirac+idirac]*(u11t[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc]+\
                                               u12t[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc+1]-\
                                               conj(u11t[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]+\
                                               u12t[did*ndim+mu]*r[(did*ngorkov+igork1)*nc+1]);
            phi[(i*ngorkov+igorkov)*nc+1]+=-akappa*(-conj(u12t[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc]+\
                  conj(u11t[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc+1]+\
                  conj(u12t[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]+\
                  u11t[did*ndim+mu]*r[(did*ngorkov+igorkov)*nc+1])+\
                                           //Dirac term
                                           gamval[mu*ndirac+idirac]*(-conj(u12t[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc]+\
                                                 conj(u11t[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc+1]-\
                                                 conj(u12t[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]-\
                                                 u11t[did*ndim+mu]*r[(did*ngorkov+igork1)*nc+1]);
         }
      }
      //Timelike terms next. These run from igorkov=0..3 and 4..7 with slightly different rules for each
      //We can fit it into a single loop by declaring igorkovPP=igorkov+4 instead of looping igorkov=4..7  separately
      //Note that for the igorkov 4..7 loop idirac=igorkov-4, so we don't need to declare idiracPP separately
#endif
      int did=id[3+ndim*i]; int uid = iu[3+ndim*i];
#ifndef NO_TIME
#pragma omp simd aligned(phi,r,u11t,u12t,dk4m,dk4p:AVX)
      for(int igorkov=0; igorkov<4; igorkov++){
         int igorkovPP=igorkov+4;   //idirac = igorkov; It is a bit redundant but I'll mention it as that's how
                                    //the FORTRAN code did it.
         int igork1 = gamin[3*ndirac+igorkov];  int igork1PP = igork1+4;
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
         phi[(i*ngorkov+igorkov)*nc]+=
            -dk4p[i]*(u11t[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc]-r[(uid*ngorkov+igork1)*nc])
                  +u12t[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc+1]-r[(uid*ngorkov+igork1)*nc+1]))
            -dk4m[did]*(conj(u11t[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]+r[(did*ngorkov+igork1)*nc])
                  -u12t[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]+r[(did*ngorkov+igork1)*nc+1]));
         phi[(i*ngorkov+igorkov)*nc+1]+=
            -dk4p[i]*(-conj(u12t[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc]-r[(uid*ngorkov+igork1)*nc])
                  +conj(u11t[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc+1]-r[(uid*ngorkov+igork1)*nc+1]))
            -dk4m[did]*(conj(u12t[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]+r[(did*ngorkov+igork1)*nc])
                  +u11t[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]+r[(did*ngorkov+igork1)*nc+1]));
         //And the +4 terms. Note that dk4p and dk4m swap positions compared to the above
         phi[(i*ngorkov+igorkovPP)*nc]+=-dk4m[i]*(u11t[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc]-r[(uid*ngorkov+igork1PP)*nc])+\
               u12t[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc+1]-r[(uid*ngorkov+igork1PP)*nc+1]))-\
                                        dk4p[did]*(conj(u11t[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]+r[(did*ngorkov+igork1PP)*nc])-\
                                              u12t[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]+r[(did*ngorkov+igork1PP)*nc+1]));
         phi[(i*ngorkov+igorkovPP)*nc+1]+=-dk4m[i]*(conj(-u12t[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc]-r[(uid*ngorkov+igork1PP)*nc])+\
               conj(u11t[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc+1]-r[(uid*ngorkov+igork1PP)*nc+1]))-\
                                          dk4p[did]*(conj(u12t[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]+r[(did*ngorkov+igork1PP)*nc])+\
                                                u11t[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]+r[(did*ngorkov+igork1PP)*nc+1]));
      }
#endif
   }
#endif
   return 0;
}
References Complex, Complex_f, kferm, kvol, nc, ndim, ndirac, ngorkov, and ZHalo_swap_all().
Dslash_f()
int Dslash_f (Complex_f * phi, Complex_f * r, Complex_f * u11t, Complex_f * u12t, unsigned int * iu, unsigned int * id, Complex_f * gamval, int * gamin, float * dk[2], Complex_f jqq, float akappa)
Evaluates \(\Phi=M r\) in single precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
jqq Diquark source
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 463 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M r@f) in single precision.
    *
    * @param   phi:        The product
    * @param   r:          The array being acted on by M
    * @param   u11t_f:     First colour trial field
    * @param   u12t_f:     Second colour trial field
    * @param   iu:         Upper halo indices
    * @param   id:         Lower halo indices
    * @param   gamval_f:   Gamma matrices
    * @param   gamin:      Indices for dirac terms
    * @param   dk_f[0]:
    * @param   dk_f[1]:
    * @param   jqq:        Diquark source
    * @param   akappa:     Hopping parameter
    *
    * @see CHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Dslash_f";
   //Get the halos in order
#if(nproc>1)
   CHalo_swap_all(r, 16);
#endif
   //Mass term
   //Diquark Term (antihermitian)
#ifdef __NVCC__
   cuDslash_f(phi,r,u11t_f,u12t_f,iu,id,gamval_f,gamin,dk_f[0],dk_f[1],jqq,akappa,dimGrid,dimBlock);
#else
   memcpy(phi, r, kferm*sizeof(Complex_f));
#pragma omp parallel for
   for(unsigned int i=0;i<kvol;i++){
#pragma omp simd aligned(phi,r,gamval_f:AVX)
      for(unsigned short idirac = 0; idirac<ndirac; idirac++){
         unsigned short igork = idirac+4;
         Complex_f a_1, a_2;
         a_1=conj(jqq)*gamval_f[4*ndirac+idirac];
         //We subtract a_2, hence the minus
         a_2=-jqq*gamval_f[4*ndirac+idirac];
         phi[(i*ngorkov+idirac)*nc]+=a_1*r[(i*ngorkov+igork)*nc+0];
         phi[(i*ngorkov+idirac)*nc+1]+=a_1*r[(i*ngorkov+igork)*nc+1];
         phi[(i*ngorkov+igork)*nc+0]+=a_2*r[(i*ngorkov+idirac)*nc];
         phi[(i*ngorkov+igork)*nc+1]+=a_2*r[(i*ngorkov+idirac)*nc+1];
      }
      //Spacelike terms. Here's hoping I haven't put time as the zeroth component somewhere!
#ifndef NO_SPACE
      for(unsigned short mu = 0; mu <3; mu++){
         unsigned int did=id[mu+ndim*i]; unsigned int uid = iu[mu+ndim*i];
#pragma omp simd aligned(phi,r,u11t_f,u12t_f,gamval_f,gamin:AVX)
         for(unsigned short igorkov=0; igorkov<ngorkov; igorkov++){
            //FORTRAN had mod((igorkov-1),4)+1 to prevent issues with non-zero indexing in the dirac term.
            unsigned short idirac=igorkov%4;
            unsigned short igork1 = (igorkov<4) ? gamin[mu*ndirac+idirac] : gamin[mu*ndirac+idirac]+4;
            //Can manually vectorise with a pragma?
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
            phi[(i*ngorkov+igorkov)*nc]+=-akappa*(u11t_f[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc]+\
                  u12t_f[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc+1]+\
                  conj(u11t_f[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]-\
                  u12t_f[did*ndim+mu]*r[(did*ngorkov+igorkov)*nc+1])+\
                                         //Dirac term. Reminder! gamval was rescaled by kappa when we defined it
                                         gamval_f[mu*ndirac+idirac]*(u11t_f[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc]+\
                                               u12t_f[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc+1]-\
                                               conj(u11t_f[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]+\
                                               u12t_f[did*ndim+mu]*r[(did*ngorkov+igork1)*nc+1]);
            phi[(i*ngorkov+igorkov)*nc+1]+=-akappa*(-conj(u12t_f[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc]+\
                  conj(u11t_f[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc+1]+\
                  conj(u12t_f[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]+\
                  u11t_f[did*ndim+mu]*r[(did*ngorkov+igorkov)*nc+1])+\
                                           //Dirac term
                                           gamval_f[mu*ndirac+idirac]*(-conj(u12t_f[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc]+\
                                                 conj(u11t_f[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc+1]-\
                                                 conj(u12t_f[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]-\
                                                 u11t_f[did*ndim+mu]*r[(did*ngorkov+igork1)*nc+1]);
         }
      }
      //Timelike terms next. These run from igorkov=0..3 and 4..7 with slightly different rules for each
      //We can fit it into a single loop by declaring igorkovPP=igorkov+4 instead of looping igorkov=4..7  separately
      //Note that for the igorkov 4..7 loop idirac=igorkov-4, so we don't need to declare idiracPP separately
#endif
      unsigned int did=id[3+ndim*i]; unsigned int uid = iu[3+ndim*i];
#ifndef NO_TIME
#pragma omp simd aligned(phi,r,u11t_f,u12t_f,gamin:AVX)
      for(unsigned short igorkov=0; igorkov<4; igorkov++){
         unsigned short igorkovPP=igorkov+4;    //idirac = igorkov; It is a bit redundant but I'll mention it as that's how
                                    //the FORTRAN code did it.
         unsigned short igork1 = gamin[3*ndirac+igorkov];   unsigned short igork1PP = igork1+4;
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
         phi[(i*ngorkov+igorkov)*nc]+=
            -dk_f[1][i]*(u11t_f[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc]-r[(uid*ngorkov+igork1)*nc])
                  +u12t_f[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc+1]-r[(uid*ngorkov+igork1)*nc+1]))
            -dk_f[0][did]*(conj(u11t_f[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]+r[(did*ngorkov+igork1)*nc])
                  -u12t_f[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]+r[(did*ngorkov+igork1)*nc+1]));
         phi[(i*ngorkov+igorkov)*nc+1]+=
            -dk_f[1][i]*(-conj(u12t_f[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc]-r[(uid*ngorkov+igork1)*nc])
                  +conj(u11t_f[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc+1]-r[(uid*ngorkov+igork1)*nc+1]))
            -dk_f[0][did]*(conj(u12t_f[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]+r[(did*ngorkov+igork1)*nc])
                  +u11t_f[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]+r[(did*ngorkov+igork1)*nc+1]));
         //And the +4 terms. Note that dk_f[1] and dk_f[0] swap positions compared to the above
         phi[(i*ngorkov+igorkovPP)*nc]+=-dk_f[0][i]*(u11t_f[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc]-r[(uid*ngorkov+igork1PP)*nc])
               +u12t_f[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc+1]-r[(uid*ngorkov+igork1PP)*nc+1]))
            -dk_f[1][did]*(conj(u11t_f[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]+r[(did*ngorkov+igork1PP)*nc])
                  -u12t_f[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]+r[(did*ngorkov+igork1PP)*nc+1]));
         phi[(i*ngorkov+igorkovPP)*nc+1]+=-dk_f[0][i]*(conj(-u12t_f[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc]-r[(uid*ngorkov+igork1PP)*nc])
               +conj(u11t_f[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc+1]-r[(uid*ngorkov+igork1PP)*nc+1]))
            -dk_f[1][did]*(conj(u12t_f[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]+r[(did*ngorkov+igork1PP)*nc])
                  +u11t_f[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]+r[(did*ngorkov+igork1PP)*nc+1]));
      }
#endif
   }
#endif
   return 0;
}
References CHalo_swap_all(), Complex_f, kferm, kvol, nc, ndim, ndirac, and ngorkov.
Dslashd()
int Dslashd (Complex * phi, Complex * r, Complex * u11t, Complex * u12t, unsigned int * iu, unsigned int * id, Complex * gamval, int * gamin, double * dk4m, double * dk4p, Complex_f jqq, float akappa)
Evaluates \(\Phi=M^\dagger r\) in double precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
jqq Diquark source
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 141 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M^\dagger r@f) in double precision.
    *
    * @param   phi:        The product
    * @param   r:          The array being acted on by M
    * @param   u11t:    First colour trial field
    * @param   u12t:    Second colour trial field
    * @param   iu:         Upper halo indices
    * @param   id:         Lower halo indices
    * @param   gamval:  Gamma matrices
    * @param   gamin:      Indices for dirac terms
    * @param   dk4m:
    * @param   dk4p:
    * @param   jqq:        Diquark source
    * @param   akappa:     Hopping parameter
    *
    * @see ZHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Dslashd";
   //Get the halos in order
#if(nproc>1)
   ZHalo_swap_all(r, 16);
#endif
   //Mass term
#ifdef __NVCC__
   cuDslashd(phi,r,u11t,u12t,iu,id,gamval,gamin,dk4m,dk4p,jqq,akappa,dimGrid,dimBlock);
#else
   memcpy(phi, r, kferm*sizeof(Complex));
#pragma omp parallel for
   for(int i=0;i<kvol;i++){
#pragma omp simd aligned(phi,r,gamval:AVX)
      //Diquark Term (antihermitian) The signs of a_1 and a_2 below flip under dagger
      for(int idirac = 0; idirac<ndirac; idirac++){
         int igork = idirac+4;
         Complex a_1, a_2;
         //We subtract a_1, hence the minus
         a_1=-conj(jqq)*gamval[4*ndirac+idirac];
         a_2=jqq*gamval[4*ndirac+idirac];
         phi[(i*ngorkov+idirac)*nc]+=a_1*r[(i*ngorkov+igork)*nc];
         phi[(i*ngorkov+idirac)*nc+1]+=a_1*r[(i*ngorkov+igork)*nc+1];
         phi[(i*ngorkov+igork)*nc]+=a_2*r[(i*ngorkov+idirac)*nc];
         phi[(i*ngorkov+igork)*nc+1]+=a_2*r[(i*ngorkov+idirac)*nc+1];
      }
      //Spacelike terms. Here's hoping I haven't put time as the zeroth component somewhere!
#ifndef NO_SPACE
      for(int mu = 0; mu <3; mu++){
         int did=id[mu+ndim*i]; int uid = iu[mu+ndim*i];
#pragma omp simd aligned(phi,r,u11t,u12t,gamval:AVX)
         for(int igorkov=0; igorkov<ngorkov; igorkov++){
            //FORTRAN had mod((igorkov-1),4)+1 to prevent issues with non-zero indexing.
            int idirac=igorkov%4;
            int igork1 = (igorkov<4) ? gamin[mu*ndirac+idirac] : gamin[mu*ndirac+idirac]+4;
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
            //Reminder! gamval was rescaled by kappa when we defined it
            phi[(i*ngorkov+igorkov)*nc]+=
               -akappa*(      u11t[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc]
                     +u12t[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc+1]
                     +conj(u11t[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]
                     -u12t[did*ndim+mu] *r[(did*ngorkov+igorkov)*nc+1])
               -gamval[mu*ndirac+idirac]*
               (          u11t[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc]
                          +u12t[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc+1]
                          -conj(u11t[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]
                          +u12t[did*ndim+mu] *r[(did*ngorkov+igork1)*nc+1]);
            phi[(i*ngorkov+igorkov)*nc+1]+=
               -akappa*(-conj(u12t[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc]
                     +conj(u11t[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc+1]
                     +conj(u12t[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]
                     +u11t[did*ndim+mu] *r[(did*ngorkov+igorkov)*nc+1])
               -gamval[mu*ndirac+idirac]*
               (-conj(u12t[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc]
                +conj(u11t[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc+1]
                -conj(u12t[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]
                -u11t[did*ndim+mu] *r[(did*ngorkov+igork1)*nc+1]);
         }
      }
#endif
      //Timelike terms next. These run from igorkov=0..3 and 4..7 with slightly different rules for each
      //We can fit it into a single loop by declaring igorkovPP=igorkov+4 instead of looping igorkov=4..7  separately
      //Note that for the igorkov 4..7 loop idirac=igorkov-4, so we don't need to declare idiracPP separately
      //Under dagger, dk4p and dk4m get swapped and the dirac component flips sign.
      int did=id[3+ndim*i]; int uid = iu[3+ndim*i];
#ifndef NO_TIME
#pragma omp simd aligned(phi,r,u11t,u12t,dk4m,dk4p:AVX)
      for(int igorkov=0; igorkov<4; igorkov++){
         //the FORTRAN code did it.
         int igork1 = gamin[3*ndirac+igorkov];
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
         phi[(i*ngorkov+igorkov)*nc]+=
            -dk4m[i]*(u11t[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc]+r[(uid*ngorkov+igork1)*nc])
                  +u12t[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc+1]+r[(uid*ngorkov+igork1)*nc+1]))
            -dk4p[did]*(conj(u11t[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]-r[(did*ngorkov+igork1)*nc])
                  -u12t[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]-r[(did*ngorkov+igork1)*nc+1]));
         phi[(i*ngorkov+igorkov)*nc+1]+=
            -dk4m[i]*(-conj(u12t[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc]+r[(uid*ngorkov+igork1)*nc])
                  +conj(u11t[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc+1]+r[(uid*ngorkov+igork1)*nc+1]))
            -dk4p[did]*(conj(u12t[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]-r[(did*ngorkov+igork1)*nc])
                  +u11t[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]-r[(did*ngorkov+igork1)*nc+1]));
         int igorkovPP=igorkov+4;   //idirac = igorkov; It is a bit redundant but I'll mention it as that's how
         int igork1PP = igork1+4;
         //And the +4 terms. Note that dk4p and dk4m swap positions compared to the above
         phi[(i*ngorkov+igorkovPP)*nc]+=-dk4p[i]*(u11t[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc]+r[(uid*ngorkov+igork1PP)*nc])+\
               u12t[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc+1]+r[(uid*ngorkov+igork1PP)*nc+1]))-\
                                        dk4m[did]*(conj(u11t[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]-r[(did*ngorkov+igork1PP)*nc])-\
                                              u12t[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]-r[(did*ngorkov+igork1PP)*nc+1]));
         phi[(i*ngorkov+igorkovPP)*nc+1]+=dk4p[i]*(conj(u12t[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc]+r[(uid*ngorkov+igork1PP)*nc])-\
               conj(u11t[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc+1]+r[(uid*ngorkov+igork1PP)*nc+1]))-\
                                          dk4m[did]*(conj(u12t[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]-r[(did*ngorkov+igork1PP)*nc])+
                                                u11t[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]-r[(did*ngorkov+igork1PP)*nc+1]));
      }
#endif
   }
#endif
   return 0;
}
References Complex, Complex_f, kferm, kvol, nc, ndim, ndirac, ngorkov, and ZHalo_swap_all().
Dslashd_f()
int Dslashd_f (Complex_f * phi, Complex_f * r, Complex_f * u11t, Complex_f * u12t, unsigned int * iu, unsigned int * id, Complex_f * gamval, int * gamin, float * dk[2], Complex_f jqq, float akappa)
Evaluates \(\Phi=M^\dagger r\) in single precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
jqq Diquark source
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 585 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M^\dagger r@f) in single precision.
    *
    * @param   phi:        The product
    * @param   r:          The array being acted on by M
    * @param   u11t_f:     First colour trial field
    * @param   u12t_f:     Second colour trial field
    * @param   iu:         Upper halo indices
    * @param   id:         Lower halo indices
    * @param   gamval_f:   Gamma matrices
    * @param   gamin:      Indices for dirac terms
    * @param   dk_f[0]:
    * @param   dk_f[1]:
    * @param   jqq:        Diquark source
    * @param   akappa:     Hopping parameter
    *
    * @see CHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Dslashd_f";
   //Get the halos in order
#if(nproc>1)
   CHalo_swap_all(r, 16);
#endif
   //Mass term
#ifdef __NVCC__
   cuDslashd_f(phi,r,u11t_f,u12t_f,iu,id,gamval_f,gamin,dk_f[0],dk_f[1],jqq,akappa,dimGrid,dimBlock);
#else
   memcpy(phi, r, kferm*sizeof(Complex_f));
#pragma omp parallel for
   for(unsigned int i=0;i<kvol;i++){
#pragma omp simd aligned(phi,r,gamval_f:AVX)
      //Diquark Term (antihermitian) The signs of a_1 and a_2 below flip under dagger
      for(unsigned short idirac = 0; idirac<ndirac; idirac++){
         unsigned short igork = idirac+4;
         Complex_f a_1, a_2;
         //We subtract a_1, hence the minus
         a_1=-conj(jqq)*gamval_f[4*ndirac+idirac];
         a_2=jqq*gamval_f[4*ndirac+idirac];
         phi[(i*ngorkov+idirac)*nc]+=a_1*r[(i*ngorkov+igork)*nc];
         phi[(i*ngorkov+idirac)*nc+1]+=a_1*r[(i*ngorkov+igork)*nc+1];
         phi[(i*ngorkov+igork)*nc]+=a_2*r[(i*ngorkov+idirac)*nc];
         phi[(i*ngorkov+igork)*nc+1]+=a_2*r[(i*ngorkov+idirac)*nc+1];
      }
      //Spacelike terms. Here's hoping I haven't put time as the zeroth component somewhere!
#ifndef NO_SPACE
      for(unsigned short mu = 0; mu <3; mu++){
         unsigned int did=id[mu+ndim*i]; unsigned int uid = iu[mu+ndim*i];
#pragma omp simd aligned(phi,r,u11t_f,u12t_f,gamval_f:AVX)
         for(unsigned short igorkov=0; igorkov<ngorkov; igorkov++){
            //FORTRAN had mod((igorkov-1),4)+1 to prevent issues with non-zero indexing.
            unsigned short idirac=igorkov%4;
            unsigned short igork1 = (igorkov<4) ? gamin[mu*ndirac+idirac] : gamin[mu*ndirac+idirac]+4;
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
            //Reminder! gamval was rescaled by kappa when we defined it
            phi[(i*ngorkov+igorkov)*nc]+=
               -akappa*(      u11t_f[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc]
                     +u12t_f[i*ndim+mu]*r[(uid*ngorkov+igorkov)*nc+1]
                     +conj(u11t_f[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]
                     -u12t_f[did*ndim+mu] *r[(did*ngorkov+igorkov)*nc+1])
               -gamval_f[mu*ndirac+idirac]*
               (          u11t_f[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc]
                          +u12t_f[i*ndim+mu]*r[(uid*ngorkov+igork1)*nc+1]
                          -conj(u11t_f[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]
                          +u12t_f[did*ndim+mu] *r[(did*ngorkov+igork1)*nc+1]);
            phi[(i*ngorkov+igorkov)*nc+1]+=
               -akappa*(-conj(u12t_f[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc]
                     +conj(u11t_f[i*ndim+mu])*r[(uid*ngorkov+igorkov)*nc+1]
                     +conj(u12t_f[did*ndim+mu])*r[(did*ngorkov+igorkov)*nc]
                     +u11t_f[did*ndim+mu] *r[(did*ngorkov+igorkov)*nc+1])
               -gamval_f[mu*ndirac+idirac]*
               (-conj(u12t_f[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc]
                +conj(u11t_f[i*ndim+mu])*r[(uid*ngorkov+igork1)*nc+1]
                -conj(u12t_f[did*ndim+mu])*r[(did*ngorkov+igork1)*nc]
                -u11t_f[did*ndim+mu] *r[(did*ngorkov+igork1)*nc+1]);
         }
      }
#endif
      //Timelike terms next. These run from igorkov=0..3 and 4..7 with slightly different rules for each
      //We can fit it into a single loop by declaring igorkovPP=igorkov+4 instead of looping igorkov=4..7  separately
      //Note that for the igorkov 4..7 loop idirac=igorkov-4, so we don't need to declare idiracPP separately
      //Under dagger, dk_f[1] and dk_f[0] get swapped and the dirac component flips sign.
      unsigned int did=id[3+ndim*i]; unsigned int uid = iu[3+ndim*i];
#ifndef NO_TIME
#pragma omp simd aligned(phi,r,u11t_f,u12t_f:AVX)
      for(unsigned short igorkov=0; igorkov<4; igorkov++){
         //the FORTRAN code did it.
         unsigned short igork1 = gamin[3*ndirac+igorkov];
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
         phi[(i*ngorkov+igorkov)*nc]+=
            -dk_f[0][i]*(u11t_f[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc]+r[(uid*ngorkov+igork1)*nc])
                  +u12t_f[i*ndim+3]*(r[(uid*ngorkov+igorkov)*nc+1]+r[(uid*ngorkov+igork1)*nc+1]))
            -dk_f[1][did]*(conj(u11t_f[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]-r[(did*ngorkov+igork1)*nc])
                  -u12t_f[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]-r[(did*ngorkov+igork1)*nc+1]));
         phi[(i*ngorkov+igorkov)*nc+1]+=
            -dk_f[0][i]*(-conj(u12t_f[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc]+r[(uid*ngorkov+igork1)*nc])
                  +conj(u11t_f[i*ndim+3])*(r[(uid*ngorkov+igorkov)*nc+1]+r[(uid*ngorkov+igork1)*nc+1]))
            -dk_f[1][did]*(conj(u12t_f[did*ndim+3])*(r[(did*ngorkov+igorkov)*nc]-r[(did*ngorkov+igork1)*nc])
                  +u11t_f[did*ndim+3] *(r[(did*ngorkov+igorkov)*nc+1]-r[(did*ngorkov+igork1)*nc+1]));
         unsigned short igorkovPP=igorkov+4;    //idirac = igorkov; It is a bit redundant but I'll mention it as that's how
         unsigned short igork1PP = igork1+4;
         //And the +4 terms. Note that dk_f[1] and dk_f[0] swap positions compared to the above
         phi[(i*ngorkov+igorkovPP)*nc]+=-dk_f[1][i]*(u11t_f[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc]+r[(uid*ngorkov+igork1PP)*nc])
               +u12t_f[i*ndim+3]*(r[(uid*ngorkov+igorkovPP)*nc+1]+r[(uid*ngorkov+igork1PP)*nc+1]))
            -dk_f[0][did]*(conj(u11t_f[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]-r[(did*ngorkov+igork1PP)*nc])
                  -u12t_f[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]-r[(did*ngorkov+igork1PP)*nc+1]));
         phi[(i*ngorkov+igorkovPP)*nc+1]+=dk_f[1][i]*(conj(u12t_f[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc]+r[(uid*ngorkov+igork1PP)*nc])
               -conj(u11t_f[i*ndim+3])*(r[(uid*ngorkov+igorkovPP)*nc+1]+r[(uid*ngorkov+igork1PP)*nc+1]))
            -dk_f[0][did]*(conj(u12t_f[did*ndim+3])*(r[(did*ngorkov+igorkovPP)*nc]-r[(did*ngorkov+igork1PP)*nc])
                  +u11t_f[did*ndim+3]*(r[(did*ngorkov+igorkovPP)*nc+1]-r[(did*ngorkov+igork1PP)*nc+1]));
      }
#endif
   }
#endif
   return 0;
}
References CHalo_swap_all(), Complex_f, kferm, kvol, nc, ndim, ndirac, and ngorkov.
Hdslash()
int Hdslash (Complex * phi, Complex * r, Complex * u11t[2], unsigned int * iu, unsigned int * id, Complex * gamval, int * gamin, double * dk[2], float akappa)
Evaluates \(\Phi=M r\) in double precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 268 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M r@f) in double precision
    *
    * @param   phi:     The product
    * @param   r:       The array being acted on by M
    * @param   ut[0]:   First colour trial field
    * @param   ut[1]:   Second colour trial field
    * @param   iu:      Upper halo indices
    * @param   id:      Lower halo indices
    * @param   gamval:  Gamma matrices
    * @param   gamin:   Indices for dirac terms
    * @param   dk[0]:
    * @param   dk[1]:
    * @param   akappa:  Hopping parameter
    *
    * @see ZHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Hdslash";
   //Get the halos in order
#if(nproc>1)
   ZHalo_swap_all(r, 8);
#endif
   //Mass term
   //Spacelike term
#ifdef __NVCC__
   cuHdslash(phi,r,ut[0],ut[1],iu,id,gamval,gamin,dk[0],dk[1],akappa,dimGrid,dimBlock);
#else
   memcpy(phi, r, kferm2*sizeof(Complex));
#pragma omp parallel for
   for(int i=0;i<kvol;i++){
#ifndef NO_SPACE
      for(int mu = 0; mu <3; mu++){
         int did=id[mu+ndim*i]; int uid = iu[mu+ndim*i];
#pragma omp simd aligned(phi,r,gamval:AVX)
         for(int idirac=0; idirac<ndirac; idirac++){
            //FORTRAN had mod((idirac-1),4)+1 to prevent issues with non-zero indexing.
            int igork1 = gamin[mu*ndirac+idirac];
            //Can manually vectorise with a pragma?
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
            phi[(i*ndirac+idirac)*nc]+=-akappa*(ut[0][i*ndim+mu]*r[(uid*ndirac+idirac)*nc]+\
                  ut[1][i*ndim+mu]*r[(uid*ndirac+idirac)*nc+1]+\
                  conj(ut[0][did*ndim+mu])*r[(did*ndirac+idirac)*nc]-\
                  ut[1][did*ndim+mu]*r[(did*ndirac+idirac)*nc+1])+\
                                       //Dirac term
                                       gamval[mu*ndirac+idirac]*(ut[0][i*ndim+mu]*r[(uid*ndirac+igork1)*nc]+\
                                             ut[1][i*ndim+mu]*r[(uid*ndirac+igork1)*nc+1]-\
                                             conj(ut[0][did*ndim+mu])*r[(did*ndirac+igork1)*nc]+\
                                             ut[1][did*ndim+mu]*r[(did*ndirac+igork1)*nc+1]);
            phi[(i*ndirac+idirac)*nc+1]+=-akappa*(-conj(ut[1][i*ndim+mu])*r[(uid*ndirac+idirac)*nc]+\
                  conj(ut[0][i*ndim+mu])*r[(uid*ndirac+idirac)*nc+1]+\
                  conj(ut[1][did*ndim+mu])*r[(did*ndirac+idirac)*nc]+\
                  ut[0][did*ndim+mu]*r[(did*ndirac+idirac)*nc+1])+\
                                         //Dirac term
                                         gamval[mu*ndirac+idirac]*(-conj(ut[1][i*ndim+mu])*r[(uid*ndirac+igork1)*nc]+\
                                               conj(ut[0][i*ndim+mu])*r[(uid*ndirac+igork1)*nc+1]-\
                                               conj(ut[1][did*ndim+mu])*r[(did*ndirac+igork1)*nc]-\
                                               ut[0][did*ndim+mu]*r[(did*ndirac+igork1)*nc+1]);
         }
      }
#endif
      //Timelike terms
      int did=id[3+ndim*i]; int uid = iu[3+ndim*i];
#ifndef NO_TIME
#pragma omp simd aligned(phi,r:AVX)
      for(int idirac=0; idirac<ndirac; idirac++){
         int igork1 = gamin[3*ndirac+idirac];
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
         //Reminder! gamval was rescaled by kappa when we defined it
         phi[(i*ndirac+idirac)*nc]+=
            -dk[1][i]*(ut[0][i*ndim+3]*(r[(uid*ndirac+idirac)*nc]-r[(uid*ndirac+igork1)*nc])
                  +ut[1][i*ndim+3]*(r[(uid*ndirac+idirac)*nc+1]-r[(uid*ndirac+igork1)*nc+1]))
            -dk[0][did]*(conj(ut[0][did*ndim+3])*(r[(did*ndirac+idirac)*nc]+r[(did*ndirac+igork1)*nc])
                  -ut[1][did*ndim+3] *(r[(did*ndirac+idirac)*nc+1]+r[(did*ndirac+igork1)*nc+1]));
         phi[(i*ndirac+idirac)*nc+1]+=
            -dk[1][i]*(-conj(ut[1][i*ndim+3])*(r[(uid*ndirac+idirac)*nc]-r[(uid*ndirac+igork1)*nc])
                  +conj(ut[0][i*ndim+3])*(r[(uid*ndirac+idirac)*nc+1]-r[(uid*ndirac+igork1)*nc+1]))
            -dk[0][did]*(conj(ut[1][did*ndim+3])*(r[(did*ndirac+idirac)*nc]+r[(did*ndirac+igork1)*nc])
                  +ut[0][did*ndim+3] *(r[(did*ndirac+idirac)*nc+1]+r[(did*ndirac+igork1)*nc+1]));
      }
#endif
   }
#endif
   return 0;
}
References Complex, kferm2, kvol, nc, ndim, ndirac, and ZHalo_swap_all().
Hdslash_f()
int Hdslash_f (Complex_f * phi, Complex_f * r, Complex_f * ut[2], unsigned int * iu, unsigned int * id, Complex_f * gamval, int * gamin, float * dk[2], float akappa)
Evaluates \(\Phi=M r\) in single precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 712 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M r@f) in single precision.
    *
    * @param   phi:     The product
    * @param   r:       The array being acted on by M
    * @param   ut[0]_f: First colour trial field
    * @param   ut[1]_f: Second colour trial field
    * @param   iu:      Upper halo indices
    * @param   id:      Lower halo indices
    * @param   gamval_f:   Gamma matrices
    * @param   gamin:   Indices for dirac terms
    * @param   dk4m_f:
    * @param   dk4p_f:
    * @param   akappa:  Hopping parameter
    *
    * @see CHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Hdslash_f";
   //Get the halos in order
#if(nproc>1)
   CHalo_swap_all(r, 8);
#endif
#ifdef __NVCC__
   cuHdslash_f(phi,r,ut,iu,id,gamval,gamin,dk,akappa,dimGrid,dimBlock);
#else
   //Mass term
   memcpy(phi, r, kferm2*sizeof(Complex_f));
#pragma omp parallel for
   for(unsigned int i=0;i<kvol;i+=AVX){
      alignas(AVX) Complex_f u11s[AVX];    alignas(AVX) Complex_f u12s[AVX];
      alignas(AVX) Complex_f u11sd[AVX];   alignas(AVX) Complex_f u12sd[AVX];
      alignas(AVX) Complex_f ru[2][AVX];   alignas(AVX) Complex_f rd[2][AVX];
      alignas(AVX) Complex_f rgu[2][AVX];  alignas(AVX) Complex_f rgd[2][AVX];
      alignas(AVX) Complex_f phi_s[ndirac*nc][AVX];
      //Do we need to sync threads if each thread only accesses the value it put in shared memory?
#pragma unroll(2)
      for(unsigned short idirac=0; idirac<ndirac; idirac++)
         for(unsigned short c=0; c<nc; c++)
#pragma omp simd aligned(phi_s,phi:AVX)
            for(unsigned short j=0;j<AVX;j++)
               phi_s[idirac*nc+c][j]=phi[((i+j)*ndirac+idirac)*nc+c];
      alignas(AVX) unsigned int did[AVX], uid[AVX];
#pragma unroll
      for(unsigned short mu = 0; mu <3; mu++){
#pragma omp simd aligned(u11s,u12s,did,uid,id,iu,u11sd,u12sd:AVX)
         for(unsigned short j =0;j<AVX;j++){
            did[j]=id[(i+j)*ndim+mu]; uid[j] = iu[(i+j)*ndim+mu];
            u11s[j]=ut[0][(i+j)*ndim+mu];   u12s[j]=ut[1][(i+j)*ndim+mu];
            u11sd[j]=ut[0][did[j]*ndim+mu]; u12sd[j]=ut[1][did[j]*ndim+mu];
         }
#pragma unroll
         for(unsigned short idirac=0; idirac<ndirac; idirac++){
            unsigned short igork1 = gamin[mu*ndirac+idirac];
#pragma unroll
            for(unsigned short c=0; c<nc; c++)
#pragma omp simd aligned(ru,rd,rgu,rgd,r,uid,did:AVX)
               for(unsigned short j =0;j<AVX;j++){
                  ru[c][j]=r[(uid[j]*ndirac+idirac)*nc+c];
                  rd[c][j]=r[(did[j]*ndirac+idirac)*nc+c];
                  rgu[c][j]=r[(uid[j]*ndirac+igork1)*nc+c];
                  rgd[c][j]=r[(did[j]*ndirac+igork1)*nc+c];
               }
            //FORTRAN had mod((idirac-1),4)+1 to prevent issues with non-zero indexing.
            //Can manually vectorise with a pragma?
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
#pragma omp simd aligned(phi_s,u11s,u12s,u11sd,u12sd,ru,rd,rgu,rgd:AVX)
            for(unsigned short j =0;j<AVX;j++){
               phi_s[idirac*nc][j]+=-akappa*(u11s[j]*ru[0][j]+\
                     u12s[j]*ru[1][j]+\
                     conj(u11sd[j])*rd[0][j]-\
                     u12sd[j]*rd[1][j]);
               //Dirac term
               phi_s[idirac*nc][j]+=gamval[mu*ndirac+idirac]*(u11s[j]*rgu[0][j]+\
                     u12s[j]*rgu[1][j]-\
                     conj(u11sd[j])*rgd[0][j]+\
                     u12sd[j]*rgd[1][j]);
               phi_s[idirac*nc+1][j]+=-akappa*(-conj(u12s[j])*ru[0][j]+\
                     conj(u11s[j])*ru[1][j]+\
                     conj(u12sd[j])*rd[0][j]+\
                     u11sd[j]*rd[1][j]);
               //Dirac term
               phi_s[idirac*nc+1][j]+=gamval[mu*ndirac+idirac]*(-conj(u12s[j])*rgu[0][j]+\
                     conj(u11s[j])*rgu[1][j]-\
                     conj(u12sd[j])*rgd[0][j]-\
                     u11sd[j]*rgd[1][j]);
            }
         }
      }
#ifndef NO_TIME
      //Timelike terms
      alignas(AVX) float dk4ms[AVX],dk4ps[AVX];
#pragma omp simd
      for(unsigned short j=0;j<AVX;j++){
         u11s[j]=ut[0][(i+j)*ndim+3]; u12s[j]=ut[1][(i+j)*ndim+3];
         did[j]=id[(i+j)*ndim+3];uid[j]= iu[(i+j)*ndim+3];
         u11sd[j]=ut[0][did[j]*ndim+3];  u12sd[j]=ut[1][did[j]*ndim+3];
         dk4ms[j]=dk[0][did[j]];   dk4ps[j]=dk[1][i+j];
      }
#pragma unroll
      for(unsigned short idirac=0; idirac<ndirac; idirac++){
         unsigned short igork1 = gamin[3*ndirac+idirac];
#pragma unroll
         for(unsigned short c=0; c<nc; c++)
#pragma omp simd aligned(ru,rd,rgu,rgd,r,uid,did:AVX)
            for(unsigned short j =0;j<AVX;j++){
               ru[c][j]=r[(uid[j]*ndirac+idirac)*nc+c];
               rd[c][j]=r[(did[j]*ndirac+idirac)*nc+c];
               rgu[c][j]=r[(uid[j]*ndirac+igork1)*nc+c];
               rgd[c][j]=r[(did[j]*ndirac+igork1)*nc+c];
            }
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
#pragma omp simd aligned(phi_s,u11s,u12s,u11sd,u12sd,ru,rd,rgu,rgd,dk4ms,dk4ps,phi:AVX)
         for(unsigned short j =0;j<AVX;j++){
            phi_s[idirac*nc+0][j]-=
               dk4ps[j]*(u11s[j]*(ru[0][j]-rgu[0][j])
                     +u12s[j]*(ru[1][j]-rgu[1][j]));
            phi_s[idirac*nc+0][j]-=
               dk4ms[j]*(conj(u11sd[j])*(rd[0][j]+rgd[0][j])
                     -u12sd[j]*(rd[1][j]+rgd[1][j]));
            phi[((i+j)*ndirac+idirac)*nc]=phi_s[idirac*nc][j];
            phi_s[idirac*nc+1][j]-=
               dk4ps[j]*(-conj(u12s[j])*(ru[0][j]-rgu[0][j])
                     +conj(u11s[j])*(ru[1][j]-rgu[1][j]));
            phi_s[idirac*nc+1][j]-=
               dk4ms[j]*(conj(u12sd[j])*(rd[0][j]+rgd[0][j])
                     +u11sd[j]*(rd[1][j]+rgd[1][j]));
            phi[((i+j)*ndirac+idirac)*nc+1]=phi_s[idirac*nc+1][j];
         }
      }
#endif
   }
#endif
   return 0;
}
References AVX, CHalo_swap_all(), Complex_f, kferm2, kvol, nc, ndim, and ndirac.
Hdslashd()
int Hdslashd (Complex * phi, Complex * r, Complex * u11t, Complex * u12t, unsigned int * iu, unsigned int * id, Complex * gamval, int * gamin, double * dk4m, double * dk4p, float akappa)
Evaluates \(\Phi=M^\dagger r\) in double precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 359 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M^\dagger r@f) in double precision
    *
    * @param   phi:     The product
    * @param   r:       The array being acted on by M
    * @param   u11t: First colour trial field
    * @param   u12t: Second colour trial field
    * @param   iu:      Upper halo indices
    * @param   id:      Lower halo indices
    * @param   gamval:  Gamma matrices
    * @param   gamin:   Indices for dirac terms
    * @param   dk4m:
    * @param   dk4p:
    * @param   akappa:  Hopping parameter
    *
    * @see ZHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Hdslashd";
   //Get the halos in order. Because C is row major, we need to extract the correct
   //terms for each halo first. Changing the indices was considered but that caused
   //issues with the BLAS routines.
#if(nproc>1)
   ZHalo_swap_all(r, 8);
#endif
   //Looks like flipping the array ordering for C has meant a lot
   //of for loops. Sense we're jumping around quite a bit the cache is probably getting refreshed
   //anyways so memory access patterns mightn't be as big of an limiting factor here anyway
   //Mass term
#ifdef __NVCC__
   cuHdslashd(phi,r,u11t,u12t,iu,id,gamval,gamin,dk4m,dk4p,akappa,dimGrid,dimBlock);
#else
   memcpy(phi, r, kferm2*sizeof(Complex));
   //Spacelike term
#pragma omp parallel for
   for(int i=0;i<kvol;i++){
#ifndef NO_SPACE
      for(int mu = 0; mu <ndim-1; mu++){
         int did=id[mu+ndim*i]; int uid = iu[mu+ndim*i];
#pragma omp simd aligned(phi,r,u11t,u12t,gamval:AVX)
         for(int idirac=0; idirac<ndirac; idirac++){
            //FORTRAN had mod((idirac-1),4)+1 to prevent issues with non-zero indexing.
            int igork1 = gamin[mu*ndirac+idirac];
            //Can manually vectorise with a pragma?
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
            //Reminder! gamval was rescaled by kappa when we defined it
            phi[(i*ndirac+idirac)*nc]+=
               -akappa*(u11t[i*ndim+mu]*r[(uid*ndirac+idirac)*nc]
                     +u12t[i*ndim+mu]*r[(uid*ndirac+idirac)*nc+1]
                     +conj(u11t[did*ndim+mu])*r[(did*ndirac+idirac)*nc]
                     -u12t[did*ndim+mu] *r[(did*ndirac+idirac)*nc+1])
               -gamval[mu*ndirac+idirac]*
               (          u11t[i*ndim+mu]*r[(uid*ndirac+igork1)*nc]
                          +u12t[i*ndim+mu]*r[(uid*ndirac+igork1)*nc+1]
                          -conj(u11t[did*ndim+mu])*r[(did*ndirac+igork1)*nc]
                          +u12t[did*ndim+mu] *r[(did*ndirac+igork1)*nc+1]);
            phi[(i*ndirac+idirac)*nc+1]+=
               -akappa*(-conj(u12t[i*ndim+mu])*r[(uid*ndirac+idirac)*nc]
                     +conj(u11t[i*ndim+mu])*r[(uid*ndirac+idirac)*nc+1]
                     +conj(u12t[did*ndim+mu])*r[(did*ndirac+idirac)*nc]
                     +u11t[did*ndim+mu] *r[(did*ndirac+idirac)*nc+1])
               -gamval[mu*ndirac+idirac]*
               (-conj(u12t[i*ndim+mu])*r[(uid*ndirac+igork1)*nc]
                +conj(u11t[i*ndim+mu])*r[(uid*ndirac+igork1)*nc+1]
                -conj(u12t[did*ndim+mu])*r[(did*ndirac+igork1)*nc]
                -u11t[did*ndim+mu] *r[(did*ndirac+igork1)*nc+1]);
         }
      }
#endif
      //Timelike terms
      int did=id[3+ndim*i]; int uid = iu[3+ndim*i];
#ifndef NO_TIME
#pragma omp simd aligned(phi,r,u11t,u12t,dk4m,dk4p:AVX)
      for(int idirac=0; idirac<ndirac; idirac++){
         int igork1 = gamin[3*ndirac+idirac];
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
         //dk4m and dk4p swap under dagger
         phi[(i*ndirac+idirac)*nc]+=
            -dk4m[i]*(u11t[i*ndim+3]*(r[(uid*ndirac+idirac)*nc]+r[(uid*ndirac+igork1)*nc])
                  +u12t[i*ndim+3]*(r[(uid*ndirac+idirac)*nc+1]+r[(uid*ndirac+igork1)*nc+1]))
            -dk4p[did]*(conj(u11t[did*ndim+3])*(r[(did*ndirac+idirac)*nc]-r[(did*ndirac+igork1)*nc])
                  -u12t[did*ndim+3] *(r[(did*ndirac+idirac)*nc+1]-r[(did*ndirac+igork1)*nc+1]));
         phi[(i*ndirac+idirac)*nc+1]+=
            -dk4m[i]*(-conj(u12t[i*ndim+3])*(r[(uid*ndirac+idirac)*nc]+r[(uid*ndirac+igork1)*nc])
                  +conj(u11t[i*ndim+3])*(r[(uid*ndirac+idirac)*nc+1]+r[(uid*ndirac+igork1)*nc+1]))
            -dk4p[did]*(conj(u12t[did*ndim+3])*(r[(did*ndirac+idirac)*nc]-r[(did*ndirac+igork1)*nc])
                  +u11t[did*ndim+3] *(r[(did*ndirac+idirac)*nc+1]-r[(did*ndirac+igork1)*nc+1]));
      }
#endif
   }
#endif
   return 0;
}
References Complex, kferm2, kvol, nc, ndim, ndirac, and ZHalo_swap_all().
Hdslashd_f()
int Hdslashd_f (Complex_f * phi, Complex_f * r, Complex_f * ut[2], unsigned int * iu, unsigned int * id, Complex_f * gamval, int * gamin, float * dk[2], float akappa)
Evaluates \(\Phi=M^\dagger r\) in single precision.
Parameters
phi The product
r The array being acted on by M
u11t First colour trial field
u12t Second colour trial field
iu Upper halo indices
id Lower halo indices
gamval Gamma matrices rescaled by kappa
gamin Indices for dirac terms
dk4m \(\left(1+\gamma_0\right)e^{-\mu}\)
dk4p \(\left(1-\gamma_0\right)e^\mu\)
akappa Hopping parameter
Returns
Zero on success, integer error code otherwise
Definition at line 855 of file matrices.c.
{
   /*
    * @brief Evaluates @f(\Phi=M^\dagger r@f) in single precision
    *
    * @param   phi:     The product
    * @param   r:       The array being acted on by M
    * @param   ut[0]_f: First colour trial field
    * @param   ut[1]_f: Second colour trial field
    * @param   iu:      Upper halo indices
    * @param   id:      Lower halo indices
    * @param   gamval_f:   Gamma matrices
    * @param   gamin:   Indices for dirac terms
    * @param   dk4m_f:
    * @param   dk4p_f:
    * @param   akappa:  Hopping parameter
    *
    * @see CHalo_swap_all (MPI only)
    *
    * @return Zero on success, integer error code otherwise
    */
   const char *funcname = "Hdslashd_f";
   //Get the halos in order. Because C is row major, we need to extract the correct
   //terms for each halo first. Changing the indices was considered but that caused
   //issues with the BLAS routines.
#if(nproc>1)
   CHalo_swap_all(r, 8);
#endif
   //Looks like flipping the array ordering for C has meant a lot
   //of for loops. Sense we're jumping around quite a bit the cache is probably getting refreshed
   //anyways so memory access patterns mightn't be as big of an limiting factor here anyway
   //Mass term
#ifdef __NVCC__
   cuHdslashd_f(phi,r,ut,iu,id,gamval,gamin,dk,akappa,dimGrid,dimBlock);
#else
   memcpy(phi, r, kferm2*sizeof(Complex_f));
   //Spacelike term
   //Enough room on L1 data cache for Zen 2 to hold 160 elements at a time
   //Vectorise with 128 maybe?
#pragma omp parallel for
   for(unsigned int i=0;i<kvol;i+=AVX){
      //Right. Time to prefetch
      alignas(AVX) Complex_f u11s[AVX];      alignas(AVX) Complex_f u12s[AVX];
      alignas(AVX) Complex_f u11sd[AVX];     alignas(AVX) Complex_f u12sd[AVX];
      alignas(AVX) Complex_f ru[2][AVX];     alignas(AVX) Complex_f rd[2][AVX];
      alignas(AVX) Complex_f rgu[2][AVX];    alignas(AVX) Complex_f rgd[2][AVX];
      alignas(AVX) Complex_f phi_s[ndirac*nc][AVX];
#pragma unroll
      for(unsigned short idirac=0; idirac<ndirac; idirac++)
#pragma unroll
         for(unsigned short c=0; c<nc; c++)
#pragma omp simd aligned(phi_s,phi:AVX)
            for(unsigned short j=0;j<AVX;j++)
               phi_s[idirac*nc+c][j]=phi[((i+j)*ndirac+idirac)*nc+c];
      alignas(AVX) unsigned int did[AVX], uid[AVX];
#ifndef NO_SPACE
#pragma unroll
      for(unsigned short mu = 0; mu <ndim-1; mu++){
         //FORTRAN had mod((idirac-1),4)+1 to prevent issues with non-zero indexing.
#pragma omp simd aligned(u11s,u12s,did,uid,id,iu,u11sd,u12sd:AVX)
         for(unsigned short j =0;j<AVX;j++){
            did[j]=id[(i+j)*ndim+mu]; uid[j] = iu[(i+j)*ndim+mu];
            u11s[j]=ut[0][(i+j)*ndim+mu];   u12s[j]=ut[1][(i+j)*ndim+mu];
            u11sd[j]=ut[0][did[j]*ndim+mu]; u12sd[j]=ut[1][did[j]*ndim+mu];
         }
#pragma unroll
         for(unsigned short idirac=0; idirac<ndirac; idirac++){
            unsigned short igork1 = gamin[mu*ndirac+idirac];
#pragma unroll
            for(unsigned short c=0; c<nc; c++)
#pragma omp simd aligned(ru,rd,rgu,rgd,r,uid,did:AVX)
               for(unsigned short j =0;j<AVX;j++){
                  ru[c][j]=r[(uid[j]*ndirac+idirac)*nc+c];
                  rd[c][j]=r[(did[j]*ndirac+idirac)*nc+c];
                  rgu[c][j]=r[(uid[j]*ndirac+igork1)*nc+c];
                  rgd[c][j]=r[(did[j]*ndirac+igork1)*nc+c];
               }
            //Can manually vectorise with a pragma?
            //Wilson + Dirac term in that order. Definitely easier
            //to read when split into different loops, but should be faster this way
#pragma omp simd aligned(phi_s,u11s,u12s,u11sd,u12sd,ru,rd,rgu,rgd:AVX)
            for(unsigned short j =0;j<AVX;j++){
               phi_s[idirac*nc][j]-=akappa*(u11s[j]*ru[0][j]
                     +u12s[j]*ru[1][j]
                     +conj(u11sd[j])*rd[0][j]
                     -u12sd[j] *rd[1][j]);
               //Dirac term
               phi_s[idirac*nc][j]-=gamval[mu*ndirac+idirac]*
                  (u11s[j]*rgu[0][j]
                   +u12s[j]*rgu[1][j]
                   -conj(u11sd[j])*rgd[0][j]
                   +u12sd[j] *rgd[1][j]);
               phi_s[idirac*nc+1][j]-=akappa*(-conj(u12s[j])*ru[0][j]
                     +conj(u11s[j])*ru[1][j]
                     +conj(u12sd[j])*rd[0][j]
                     +u11sd[j] *rd[1][j]);
               //Dirac term
               phi_s[idirac*nc+1][j]-=gamval[mu*ndirac+idirac]*(-conj(u12s[j])*rgu[0][j]
                     +conj(u11s[j])*rgu[1][j]
                     -conj(u12sd[j])*rgd[0][j]
                     -u11sd[j] *rgd[1][j]);
            }
         }
      }
#endif
#ifndef NO_TIME
      //Timelike terms
      alignas(AVX) float dk4ms[AVX],dk4ps[AVX];
#pragma omp simd aligned(u11s,u12s,did,uid,id,iu,u11sd,u12sd,dk4ms,dk4ps:AVX)
      for(unsigned short j=0;j<AVX;j++){
         u11s[j]=ut[0][(i+j)*ndim+3]; u12s[j]=ut[1][(i+j)*ndim+3];
         did[j]=id[(i+j)*ndim+3];     uid[j]= iu[(i+j)*ndim+3];
         u11sd[j]=ut[0][did[j]*ndim+3];  u12sd[j]=ut[1][did[j]*ndim+3];
         dk4ms[j]=dk[0][i+j];          dk4ps[j]=dk[1][did[j]];
      }
#pragma unroll
      for(unsigned short idirac=0; idirac<ndirac; idirac++){
         unsigned short igork1 = gamin[3*ndirac+idirac];
#pragma unroll
         for(unsigned short c=0; c<nc; c++)
#pragma omp simd aligned(ru,rd,rgu,rgd,r,uid,did:AVX)
            for(unsigned short j =0;j<AVX;j++){
               ru[c][j]=r[(uid[j]*ndirac+idirac)*nc+c];
               rd[c][j]=r[(did[j]*ndirac+idirac)*nc+c];
               rgu[c][j]=r[(uid[j]*ndirac+igork1)*nc+c];
               rgd[c][j]=r[(did[j]*ndirac+igork1)*nc+c];
            }
         //Factorising for performance, we get dk4?*u1?*(+/-r_wilson -/+ r_dirac)
         //dk4m and dk4p swap under dagger
#pragma omp simd aligned(phi_s,u11s,u12s,u11sd,u12sd,ru,rd,rgu,rgd,dk4ms,dk4ps,phi:AVX)
         for(unsigned short j =0;j<AVX;j++){
            phi_s[idirac*nc][j]+=
               -dk4ms[j]*(u11s[j]*(ru[0][j]+rgu[0][j])
                     +u12s[j]*(ru[1][j]+rgu[1][j]));
            phi_s[idirac*nc][j]+=
               -dk4ps[j]*(conj(u11sd[j])*(rd[0][j]-rgd[0][j])
                     -u12sd[j] *(rd[1][j]-rgd[1][j]));
            phi[((i+j)*ndirac+idirac)*nc]=phi_s[idirac*nc][j];
            phi_s[idirac*nc+1][j]-=
               dk4ms[j]*(-conj(u12s[j])*(ru[0][j]+rgu[0][j])
                     +conj(u11s[j])*(ru[1][j]+rgu[1][j]));
            phi_s[idirac*nc+1][j]-=
               +dk4ps[j]*(conj(u12sd[j])*(rd[0][j]-rgd[0][j])
                     +u11sd[j] *(rd[1][j]-rgd[1][j]));
            phi[((i+j)*ndirac+idirac)*nc+1]=phi_s[idirac*nc+1][j];
         }
      }
#endif
   }
#endif
   return 0;
}
References AVX, CHalo_swap_all(), Complex_f, kferm2, kvol, nc, ndim, and ndirac.
Transpose_c()
void Transpose_c (Complex_f * out, const int fast_in, const int fast_out) inline
Definition at line 1050 of file matrices.c.
{
   const volatile char *funcname="Transpose_c";
#ifdef __NVCC__
   cuTranspose_c(out,fast_in,fast_out,dimGrid,dimBlock);
#else
   Complex_f *in = (Complex_f *)aligned_alloc(AVX,fast_in*fast_out*sizeof(Complex_f));
   memcpy(in,out,fast_in*fast_out*sizeof(Complex_f));
   //Typically this is used to write back to the AoS/Coalseced format
   if(fast_out>fast_in){
      for(int x=0;x<fast_out;x++)
         for(int y=0; y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   //Typically this is used to write back to the SoA/saved config format
   else{
      for(int x=0; x<fast_out;x++)
         for(int y=0;y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   free(in);
#endif
}
Transpose_d()
void Transpose_d (double * out, const int fast_in, const int fast_out) inline
Definition at line 1119 of file matrices.c.
{
   const char *funcname="Transpose_f";
#ifdef __NVCC__
   cuTranspose_d(out,fast_in,fast_out,dimGrid,dimBlock);
#else
   double *in = (double *)aligned_alloc(AVX,fast_in*fast_out*sizeof(double));
   memcpy(in,out,fast_in*fast_out*sizeof(double));
   //Typically this is used to write back to the AoS/Coalseced format
   if(fast_out>fast_in){
      for(int x=0;x<fast_out;x++)
         for(int y=0; y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   //Typically this is used to write back to the SoA/saved config format
   else{
      for(int x=0; x<fast_out;x++)
         for(int y=0;y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   free(in);
#endif
}
Transpose_f()
void Transpose_f (float * out, const int fast_in, const int fast_out) inline
Definition at line 1096 of file matrices.c.
{
   const char *funcname="Transpose_f";
#ifdef __NVCC__
   cuTranspose_f(out,fast_in,fast_out,dimGrid,dimBlock);
#else
   float *in = (float *)aligned_alloc(AVX,fast_in*fast_out*sizeof(float));
   memcpy(in,out,fast_in*fast_out*sizeof(float));
   //Typically this is used to write back to the AoS/Coalseced format
   if(fast_out>fast_in){
      for(int x=0;x<fast_out;x++)
         for(int y=0; y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   //Typically this is used to write back to the SoA/saved config format
   else{
      for(int x=0; x<fast_out;x++)
         for(int y=0;y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   free(in);
#endif
}
Transpose_I()
void Transpose_I (int * out, const int fast_in, const int fast_out) inline
Definition at line 1142 of file matrices.c.
{
   const char *funcname="Transpose_I";
#ifdef __NVCC__
   cuTranspose_I(out,fast_in,fast_out,dimGrid,dimBlock);
#else
   int *in = (int *)aligned_alloc(AVX,fast_in*fast_out*sizeof(int));
   memcpy(in,out,fast_in*fast_out*sizeof(int));
   //Typically this is used to write back to the AoS/Coalseced format
   if(fast_out>fast_in){
      for(int x=0;x<fast_out;x++)
         for(int y=0; y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   //Typically this is used to write back to the SoA/saved config format
   else{
      for(int x=0; x<fast_out;x++)
         for(int y=0;y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   free(in);
#endif
}
Transpose_U()
void Transpose_U (unsigned int * out, const int fast_in, const int fast_out) inline
Definition at line 1165 of file matrices.c.
{
   const char *funcname="Transpose_I";
#ifdef __NVCC__
   cuTranspose_U(out,fast_in,fast_out,dimGrid,dimBlock);
#else
   unsigned int *in = (unsigned int *)aligned_alloc(AVX,fast_in*fast_out*sizeof(unsigned int));
   memcpy(in,out,fast_in*fast_out*sizeof(unsigned int));
   //Typically this is used to write back to the AoS/Coalseced format
   if(fast_out>fast_in){
      for(unsigned int x=0;x<fast_out;x++)
         for(unsigned int y=0; y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   //Typically this is used to write back to the SoA/saved config format
   else{
      for(unsigned int x=0; x<fast_out;x++)
         for(unsigned int y=0;y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   free(in);
#endif
}
Transpose_z()
void Transpose_z (Complex * out, const int fast_in, const int fast_out) inline
Definition at line 1073 of file matrices.c.
{
   const volatile char *funcname="Transpose_c";
#ifdef __NVCC__
   cuTranspose_z(out,fast_in,fast_out,dimGrid,dimBlock);
#else
   Complex *in = (Complex *)aligned_alloc(AVX,fast_in*fast_out*sizeof(Complex));
   memcpy(in,out,fast_in*fast_out*sizeof(Complex));
   //Typically this is used to write back to the AoS/Coalseced format
   if(fast_out>fast_in){
      for(int x=0;x<fast_out;x++)
         for(int y=0; y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   //Typically this is used to write back to the SoA/saved config format
   else{
      for(int x=0; x<fast_out;x++)
         for(int y=0;y<fast_in;y++)
            out[y*fast_out+x]=in[x*fast_in+y];
   }
   free(in);
#endif
}