su2hmc: INCLUDE/par_mpi.h File Reference
par_mpi.h File Reference
MPI headers.
#include <coord.h>
#include <errorcodes.h>
#include <sizes.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define MPI_Finalise() MPI_Finalize()
Avoid any accidents with US/UK spelling.
#define DOWN 0
Flag for send down.
#define UP 1
Flag for send up.
#define masterproc 0
The main rank. Used for serial tasks.
#define tag 0
default MPI tag
Functions
int Par_begin (int argc, char *argv[])
Initialises the MPI configuration.
int Par_sread (const int iread, const float beta, const float fmu, const float akappa, const Complex_f ajq, Complex *u11, Complex *u12, Complex *u11t, Complex *u12t)
Reads and assigns the gauges from file.
int Par_swrite (const int itraj, const int icheck, const float beta, const float fmu, const float akappa, const Complex_f ajq, Complex *u11, Complex *u12)
Copies u11 and u12 into arrays without halos which then get written to output.
int Par_isum (int *ival)
Performs a reduction on an integer ival to get a sum which is then distributed to all ranks.
int Par_dsum (double *dval)
Performs a reduction on a double dval to get a sum which is then distributed to all ranks.
int Par_fsum (float *dval)
Performs a reduction on a float dval to get a sum which is then distributed to all ranks.
int Par_csum (Complex_f *cval)
Performs a reduction on a complex float cval to get a sum which is then distributed to all ranks.
int Par_zsum (Complex *zval)
Performs a reduction on a complex double zval to get a sum which is then distributed to all ranks.
int Par_icopy (int *ival)
Broadcasts an integer to the other processes.
int Par_dcopy (double *dval)
Broadcasts a double to the other processes.
int Par_fcopy (float *fval)
Broadcasts a float to the other processes.
int Par_ccopy (Complex *cval)
Broadcasts a complex float to the other processes.
int Par_zcopy (Complex *zval)
Broadcasts a complex double to the other processes.
int ZHalo_swap_all (Complex *z, int ncpt)
Calls the functions to send data to both the up and down halos.
int ZHalo_swap_dir (Complex *z, int ncpt, int idir, int layer)
Swaps the halos along the axis given by idir in the direction given by layer.
int CHalo_swap_all (Complex_f *c, int ncpt)
Calls the functions to send data to both the up and down halos.
int CHalo_swap_dir (Complex_f *c, int ncpt, int idir, int layer)
Swaps the halos along the axis given by idir in the direction given by layer.
int DHalo_swap_all (double *d, int ncpt)
Calls the functions to send data to both the up and down halos.
int DHalo_swap_dir (double *d, int ncpt, int idir, int layer)
Swaps the halos along the axis given by idir in the direction given by layer.
int Trial_Exchange (Complex *u11t, Complex *u12t, Complex_f *u11t_f, Complex_f *u12t_f)
Exchanges the trial fields.
Variables
int __RANLUX__ pu [ndim]
Processors in the up direction.
int __RANLUX__ pd [ndim]
Processors in the down direction.
int * pcoord
The processor grid.
int __RANLUX__ pstart [ndim][nproc]
The initial lattice site on each sublattice in a given direction.
int __RANLUX__ pstop [ndim][nproc]
The final lattice site on each sublattice in a given direction.
int rank
The MPI rank.
int size
The number of MPI ranks in total.
Detailed Description
MPI headers.
Macro Definition Documentation
DOWN
#define DOWN 0
Flag for send down.
masterproc
#define masterproc 0
The main rank. Used for serial tasks.
MPI_Finalise
#define MPI_Finalise () MPI_Finalize()
Avoid any accidents with US/UK spelling.
tag
#define tag 0
default MPI tag
UP
#define UP 1
Flag for send up.
Function Documentation
CHalo_swap_all()
int CHalo_swap_all (Complex_f * c, int ncpt)
Calls the functions to send data to both the up and down halos.
Parameters
c The data being sent
ncpt Number of components being sent
Returns
Zero on success, integer error code otherwise
CHalo_swap_dir()
int CHalo_swap_dir (Complex_f * c, int ncpt, int idir, int layer)
Swaps the halos along the axis given by idir in the direction given by layer.
Parameters
c The data being moved about. It should be an array of dimension [kvol+halo][something else]
ncpt Number of components being sent
idir The axis being moved along in C Indexing
layer Either DOWN (0) or UP (1)
Returns
Zero on success, Integer Error code otherwise
DHalo_swap_all()
int DHalo_swap_all (double * d, int ncpt)
Calls the functions to send data to both the up and down halos.
Parameters
d The data being sent
ncpt Number of components being sent
Returns
Zero on success, integer error code otherwise
DHalo_swap_dir()
int DHalo_swap_dir (double * d, int ncpt, int idir, int layer)
Swaps the halos along the axis given by idir in the direction given by layer.
Parameters
d The data being moved about. It should be an array of dimension [kvol+halo][something else]
ncpt Number of components being sent
idir The axis being moved along in C Indexing
layer Either DOWN (0) or UP (1)
Returns
Zero on success, Integer Error code otherwise
Par_begin()
int Par_begin (int argc, char * argv[])
Initialises the MPI configuration.
Parameters
argc Number of arguments given to the programme
argv Array of arguments
Returns
Zero on success, integer error code otherwise.
References AVX, ksizet, ksizex, ksizey, ksizez, ndim, NO_MPI_INIT, NO_MPI_RANK, NO_MPI_SIZE, nproc, npt, npx, npy, npz, nt, nx, ny, nz, pcoord, pd, pstart, pstop, pu, rank, size, and SIZEPROC.
Par_ccopy()
int Par_ccopy (Complex * cval)
Broadcasts a complex float to the other processes.
Parameters
cval Complex float being broadcast
Returns
Zero on success, integer error code otherwise
Par_csum()
int Par_csum (Complex_f * cval)
Performs a reduction on a complex float cval to get a sum which is then distributed to all ranks.
Parameters
cval The pointer to the element being summed, and the container for said sum.
Returns
Zero on success. Integer error code otherwise.
Par_dcopy()
int Par_dcopy (double * dval)
Broadcasts a double to the other processes.
Parameters
dval double being broadcast
Returns
Zero on success, integer error code otherwise
Par_dsum()
int Par_dsum (double * dval)
Performs a reduction on a double dval to get a sum which is then distributed to all ranks.
Parameters
dval The pointer to the element being summed, and the container for said sum.
Returns
Zero on success. Integer error code otherwise.
Par_fcopy()
int Par_fcopy (float * fval)
Broadcasts a float to the other processes.
Parameters
fval float being broadcast
Returns
Zero on success, integer error code otherwise
Par_fsum()
int Par_fsum (float * dval)
Performs a reduction on a float dval to get a sum which is then distributed to all ranks.
Parameters
dval The pointer to the element being summed, and the container for said sum.
Returns
Zero on success. Integer error code otherwise.
Par_icopy()
int Par_icopy (int * ival)
Broadcasts an integer to the other processes.
Parameters
ival Integer being broadcast
Returns
Zero on success, integer error code otherwise
Par_isum()
int Par_isum (int * ival)
Performs a reduction on an integer ival to get a sum which is then distributed to all ranks.
Parameters
ival The pointer to the element being summed, and the container for said sum.
Returns
Zero on success. Integer error code otherwise.
Par_sread()
int Par_sread (const int iread, const float beta, const float fmu, const float akappa, const Complex_f ajq, Complex * u11, Complex * u12, Complex * u11t, Complex * u12t)
Reads and assigns the gauges from file.
Parameters
iread Configuration to read in
beta Inverse gauge coupling
fmu Chemical potential
akappa Hopping parameter
ajq Diquark source
u11,u12 Gauge fields
u11t,u12t Trial fields
Returns
Zero on success, integer error code otherwise
References AVX, CANTRECV, CANTSEND, Complex, Coord2gindex(), creal, DIFNPROC, FILELEN, gvol, kvol, masterproc, ndim, nproc, nt, NUMELEM, nx, OPENERROR, pstart, pstop, rank, seed, and size.
Par_swrite()
int Par_swrite (const int itraj, const int icheck, const float beta, const float fmu, const float akappa, const Complex_f ajq, Complex * u11, Complex * u12)
Copies u11 and u12 into arrays without halos which then get written to output.
Modified from an original version of swrite in FORTRAN
Parameters
itraj Trajectory to write
icheck Not currently used but haven't gotten around to removing it
beta Inverse gauge coupling
fmu Chemical potential
akappa Hopping parameter
ajq Diquark source
u11,u12 Gauge fields
Returns
Zero on success, integer error code otherwise
References AVX, CANTRECV, CANTSEND, Complex, Coord2gindex(), creal, FILELEN, gvol, kvol, masterproc, ndim, nproc, nt, NUMELEM, nx, OPENERROR, pstart, pstop, rank, seed, and size.
Par_zcopy()
int Par_zcopy (Complex * zval)
Broadcasts a complex double to the other processes.
Parameters
zval Complex double being broadcast
Returns
Zero on success, integer error code otherwise
Par_zsum()
int Par_zsum (Complex * zval)
Performs a reduction on a complex double zval to get a sum which is then distributed to all ranks.
Parameters
zval The pointer to the element being summed, and the container for said sum.
Returns
Zero on success. Integer error code otherwise.
Trial_Exchange()
int Trial_Exchange (Complex * u11t, Complex * u12t, Complex_f * u11t_f, Complex_f * u12t_f)
Exchanges the trial fields.
I noticed that this halo exchange was happening even though the trial fields hadn't been updated. To get around this I'm making a function that does the halo exchange and only calling it after the trial fields get updated.
Parameters
u11t,u12t Double precision trial fields
u11t_f,u12t_f Single precision trial fields
Returns
Zero on success, Integer Error code otherwise
References AVX, Complex, Complex_f, halo, kvol, ndim, and ZHalo_swap_all().
ZHalo_swap_all()
int ZHalo_swap_all (Complex * z, int ncpt)
Calls the functions to send data to both the up and down halos.
Parameters
z The data being sent
ncpt Number of components being sent
Returns
Zero on success, integer error code otherwise
ZHalo_swap_dir()
int ZHalo_swap_dir (Complex * z, int ncpt, int idir, int layer)
Swaps the halos along the axis given by idir in the direction given by layer.
Parameters
z The data being moved about. It should be an array of dimension [kvol+halo][something else]
ncpt Number of components being sent
idir The axis being moved along in C Indexing
layer Either DOWN (0) or UP (1)
Returns
Zero on success, Integer Error code otherwise
Variable Documentation
pcoord
int* pcoord extern
The processor grid.
pd
int pd extern
Processors in the down direction.
pstart
int __RANLUX__ pstart[ndim][nproc] extern
The initial lattice site on each sublattice in a given direction.
pstop
int pstop extern
The final lattice site on each sublattice in a given direction.
pu
int pu extern
Processors in the up direction.
rank
int rank extern
The MPI rank.
size
int size extern
The number of MPI ranks in total.