su2hmc: INCLUDE/random.h File Reference
random.h File Reference
Header for random number configuration.
#include <math.h>
#include <par_mpi.h>
#include <sizes.h>
Macros
#define RAN2
#define IM1 2147483563
#define IM2 2147483399
#define AM (1.0/IM1)
#define IMM1 (IM1-1)
#define IA1 40014
#define IA2 40692
#define IQ1 53668
#define IQ2 52774
#define IR1 12211
#define IR2 3791
#define NTAB 32
#define NDIV (1+IMM1/NTAB)
#define EPS 1.2e-7
#define RNMX (1.0-EPS)
Functions
int ranset (long *seed)
Dummy seed the ran2 generator.
int Par_ranset (long *seed, int iread)
Uses the rank to get a new seed. Copying from the FORTRAN description here c create new seeds in range seed to 9*seed c having a range of 0*seed gave an unfortunate pattern c in the underlying value of ds(1) (it was always 10 times bigger c on the last processor). This does not appear to happen with 9.
double ran2 (long *idum)
Generates uniformly distributed random double between zero and one as described in numerical recipes. It's also thread-safe for different seeds.
int Gauss_z (Complex *ps, unsigned int n, const Complex mu, const double sigma)
Generates a vector of normally distributed random double precision complex numbers using the Box-Muller Method.
int Gauss_d (double *ps, unsigned int n, const double mu, const double sigma)
Generates a vector of normally distributed random double precision numbers using the Box-Muller Method.
int Gauss_c (Complex_f *ps, unsigned int n, const Complex_f mu, const float sigma)
Generates a vector of normally distributed random single precision complex numbers using the Box-Muller Method.
int Gauss_f (float *ps, unsigned int n, const float mu, const float sigma)
Generates a vector of normally distributed random single precision numbers using the Box-Muller Method.
int Par_ranread (char *filename, double *ranval)
Reads ps from a file Since this function is very similar to Par_sread, I'm not really going to comment it check there if you are confused about things.
double Par_granf ()
Generates a random double which is then sent to the other ranks.
int ran_test ()
Test Functions.
Variables
long seed
RAN2 seed.
Detailed Description
Header for random number configuration.
Macro Definition Documentation
AM
#define AM (1.0/IM1)
EPS
#define EPS 1.2e-7
IA1
#define IA1 40014
IA2
#define IA2 40692
IM1
#define IM1 2147483563
IM2
#define IM2 2147483399
IMM1
#define IMM1 (IM1-1)
IQ1
#define IQ1 53668
IQ2
#define IQ2 52774
IR1
#define IR1 12211
IR2
#define IR2 3791
NDIV
#define NDIV (1+IMM1/NTAB)
NTAB
#define NTAB 32
RAN2
#define RAN2
RNMX
#define RNMX (1.0-EPS)
Function Documentation
Gauss_c()
int Gauss_c (Complex_f * ps, unsigned int n, const Complex_f mu, const float sigma)
Generates a vector of normally distributed random single precision complex numbers using the Box-Muller Method.
Parameters
ps The output array
n The array length
mu mean
sigma variance
Returns
Zero on success integer error code otherwise
References ARRAYLEN, I, M_PI, ran2(), and seed.
Gauss_d()
int Gauss_d (double * ps, unsigned int n, const double mu, const double sigma)
Generates a vector of normally distributed random double precision numbers using the Box-Muller Method.
Parameters
ps The output array
n The array length
mu mean
sigma variance
Returns
Zero on success integer error code otherwise
References ARRAYLEN, M_PI, ran2(), and seed.
Gauss_f()
int Gauss_f (float * ps, unsigned int n, const float mu, const float sigma)
Generates a vector of normally distributed random single precision numbers using the Box-Muller Method.
Parameters
ps The output array
n The array length
mu mean
sigma variance
Returns
Zero on success integer error code otherwise
References ARRAYLEN, M_PI, ran2(), and seed.
Gauss_z()
int Gauss_z (Complex * ps, unsigned int n, const Complex mu, const double sigma)
Generates a vector of normally distributed random double precision complex numbers using the Box-Muller Method.
Parameters
ps The output array
n The array length
mu mean
sigma variance
Returns
Zero on success integer error code otherwise
References ARRAYLEN, I, M_PI, ran2(), and seed.
Par_granf()
double Par_granf ()
Generates a random double which is then sent to the other ranks.
Returns
the random number generated
References Par_dcopy(), ran2(), rank, and seed.
Par_ranread()
int Par_ranread (char * filename, double * ranval)
Reads ps from a file Since this function is very similar to Par_sread, I'm not really going to comment it check there if you are confused about things.
Parameters
filename The name of the file we're reading from
ranval The destination for the file's contents
Returns
Zero on success, integer error code otherwise
References OPENERROR, Par_dcopy(), and rank.
Par_ranset()
int Par_ranset (long * seed, int iread)
Uses the rank to get a new seed. Copying from the FORTRAN description here c create new seeds in range seed to 9*seed c having a range of 0*seed gave an unfortunate pattern c in the underlying value of ds(1) (it was always 10 times bigger c on the last processor). This does not appear to happen with 9.
Parameters
seed The seed from the rank in question.
iread Do we read from file or not. Don't remember why it's here as it's not used
Returns
Zero on success, integer error code otherwise
References rank, ranset(), seed, and size.
ran2()
double ran2 (long * idum)
Generates uniformly distributed random double between zero and one as described in numerical recipes. It's also thread-safe for different seeds.
Parameters
idum Pointer to the seed
Returns
The random double between zero and one
References AM, IA1, IA2, IM1, IM2, IMM1, IQ1, IQ2, IR1, IR2, NDIV, NTAB, and RNMX.
ran_test()
int ran_test ()
Test Functions.
ranset()
int ranset (long * seed) inline
Dummy seed the ran2 generator.
Parameters
seed pointer to seed
Returns
0
References seed.
Variable Documentation
seed
long seed extern
RAN2 seed.